# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style

# Enforce 2-space indentation (Ruby standard)
Layout/IndentationWidth:
  Enabled: true
  Width: 2

# Ensure consistent indentation style
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

# Detect tabs (should use spaces only)
Layout/IndentationStyle:
  Enabled: true
  EnforcedStyle: spaces
